[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
project_x = "CHv4VioJjwJ4NG6MoyHpo18iQCN2eQ1znRSkstsYUcyN"


[registry]
url = "https://rpc.mainnet.x1.xyz/"

[provider]
cluster = "https://rpc.mainnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "ts-node scripts/initialize.ts"

